#include "GenreTranslator.hpp"
#include <unordered_map>

namespace Librium::Utils {

std::string CGenreTranslator::Translate(const std::string& code)
{
    static const std::unordered_map<std::string, std::string> kGenreMap = {
        {"sf_history", "Alternative History"},
        {"sf_action", "Action Sci-Fi"},
        {"sf_epic", "Epic Sci-Fi"},
        {"sf_heroic", "Heroic Sci-Fi"},
        {"sf_detective", "Detective Sci-Fi"},
        {"sf_cyberpunk", "Cyberpunk"},
        {"sf_space", "Space Sci-Fi"},
        {"sf_social", "Social Sci-Fi"},
        {"sf_horror", "Horror and Mysticism"},
        {"sf_humor", "Humorous Sci-Fi"},
        {"sf_fantasy", "Fantasy"},
        {"sf", "Science Fiction"},
        {"child_sf", "Children's Sci-Fi"},
        {"det_classic", "Classic Detective"},
        {"det_police", "Police Detective"},
        {"det_action", "Action Detective"},
        {"det_irony", "Ironic Detective"},
        {"det_history", "Historical Detective"},
        {"det_espionage", "Espionage Detective"},
        {"det_crime", "Crime Detective"},
        {"det_political", "Political Detective"},
        {"det_maniac", "Maniacs"},
        {"det_hard", "Hardboiled Detective"},
        {"thriller", "Thriller"},
        {"detective", "Detective"},
        {"child_det", "Children's Action/Detective"},
        {"love_detective", "Romantic Suspense"},
        {"prose", "Prose"},
        {"prose_classic", "Classic Prose"},
        {"prose_history", "Historical Prose"},
        {"prose_contemporary", "Contemporary Prose"},
        {"prose_counter", "Counterculture"},
        {"prose_rus_classic", "Russian Classic"},
        {"prose_su_classics", "Soviet Classic"},
        {"humor_prose", "Humorous Prose"},
        {"child_prose", "Children's Prose"},
        {"love", "Romance"},
        {"love_contemporary", "Contemporary Romance"},
        {"love_history", "Historical Romance"},
        {"love_short", "Short Romance"},
        {"love_erotica", "Erotica"},
        {"adv_western", "Westerns"},
        {"adv_history", "Historical Adventures"},
        {"adv_indian", "Adventures: Native Americans"},
        {"adv_maritime", "Maritime Adventures"},
        {"adv_geo", "Travel and Geography"},
        {"adv_animal", "Nature and Animals"},
        {"adventure", "Adventures: Other"},
        {"child_adv", "Children's Adventures"},
        {"children", "Children's Literature"},
        {"child_tale", "Fairy Tales"},
        {"child_verse", "Children's Poetry"},
        {"child_education", "Children's Educational Literature"},
        {"poetry", "Poetry"},
        {"dramaturgy", "Dramaturgy"},
        {"humor_verse", "Humorous Poetry"},
        {"antique_ant", "Antique Literature"},
        {"antique_european", "European Antique Literature"},
        {"antique_russian", "Old Russian Literature"},
        {"antique_east", "Old Eastern Literature"},
        {"antique_myths", "Myths, Legends, Epics"},
        {"antique", "Antique Literature: Other"},
        {"sci_history", "History"},
        {"sci_psychology", "Psychology"},
        {"sci_culture", "Cultural Studies"},
        {"sci_religion", "Religious Studies"},
        {"sci_philosophy", "Philosophy"},
        {"sci_politics", "Politics"},
        {"sci_business", "Business Literature"},
        {"sci_juris", "Jurisprudence"},
        {"sci_linguistic", "Linguistics"},
        {"sci_medicine", "Medicine"},
        {"sci_phys", "Physics"},
        {"sci_math", "Mathematics"},
        {"sci_chem", "Chemistry"},
        {"sci_biology", "Biology"},
        {"sci_tech", "Technical Literature"},
        {"science", "Educational/Scientific: Other"},
        {"comp_www", "Internet"},
        {"comp_programming", "Programming"},
        {"comp_hard", "Computer Hardware"},
        {"comp_soft", "Software"},
        {"comp_db", "Databases"},
        {"comp_osnet", "OS and Networks"},
        {"computers", "Computers: Other"},
        {"ref_encyc", "Encyclopedias"},
        {"ref_dict", "Dictionaries"},
        {"ref_ref", "Reference Books"},
        {"ref_guide", "Guides"},
        {"reference", "Reference Literature: Other"},
        {"nonf_biography", "Biographies and Memoirs"},
        {"nonf_publicism", "Publicism / Journalism"},
        {"nonf_criticism", "Criticism"},
        {"nonfiction", "Non-fiction: Other"},
        {"design", "Art and Design"},
        {"religion", "Religion"},
        {"religion_rel", "Religion"},
        {"religion_esoterics", "Esoterics"},
        {"religion_self", "Self-improvement"},
        {"humor_anecdote", "Anecdotes"},
        {"humor", "Humor: Other"},
        {"home_cooking", "Cooking"},
        {"home_pets", "Pets"},
        {"home_crafts", "Hobbies and Crafts"},
        {"home_entertain", "Entertainment"},
        {"home_health", "Health"},
        {"home_garden", "Home and Garden"},
        {"home_diy", "Do It Yourself (DIY)"},
        {"home_sport", "Sports"},
        {"home_sex", "Erotica, Sex"},
        {"home", "Home and Family: Other"}
    };

    auto it = kGenreMap.find(code);
    if (it != kGenreMap.end())
    {
        return it->second;
    }
    return code; // Fallback to short code if not found
}

} // namespace Librium::Utils